export enum UPDATE_STATUS {
  IN_PROGRESS = "IN_PROGRESS",
  DEPRECATED = "DEPRECATED",
  SHIPPED = "SHIPPED",
}

export const validStatus = [
  UPDATE_STATUS.DEPRECATED,
  UPDATE_STATUS.IN_PROGRESS,
  UPDATE_STATUS.SHIPPED,
];
